version: '3.8'

services:
  mahasiswa:
    build: ./backend/pengajuan_service
    container_name: pengajuan_service
    ports:
      - "5001:5000"
    depends_on:
      - db
      - redis  # Menambahkan dependensi pada Redis
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - REDIS_HOST=redis  # Variabel lingkungan untuk menghubungkan ke Redis
    volumes:
      - ./backend/pengajuan_service:/app

  admin:
    build: ./backend/validasi_service
    container_name: validasi_service
    ports:
      - "5002:5000"
    depends_on:
      - db
      - redis  # Menambahkan dependensi pada Redis
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - REDIS_HOST=redis  # Variabel lingkungan untuk menghubungkan ke Redis
    volumes:
      - ./backend/validasi_service:/app

  login:
    build: ./backend/login_service
    container_name: login_service
    ports:
      - "5003:5000"
    depends_on:
      - db
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    volumes:
      - ./backend/login_service:/app


  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      # - "8080:80" # Production
      - "8080:5173" # Development

  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sicuti
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3309:3306"

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  db-data:
  redis-data:
